    
 spring:
  datasource:
    url: jdbc:h2:file:C:/Users/lenovo/testDb     
    driverClassName: org.h2.Driver
    username: sa
    password: password
    

  jpa:
    hibernate:
      ddl-auto: update            
    show-sql: true                 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true                 
      path: /h2-console      
      
      
      
 dvla:
   base-url: https://uk1.ukvehicledata.co.uk/api/
   auth_apikey: 64006712-36f9-4fa0-a276-d7fc836f0e76               
   
